version: '3.8'

services:
  fetch-repos:
    build:
      context: .
      target: fetch_stage
    environment:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./all_repos.txt:/app/all_repos.txt
